---
- name: git clone rtl8812bu driver
  git:
    repo: https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959.git
    dest: /usr/local/src/rtl8812bu
    clone: yes
    update: yes
    force: yes
    version: "{{ rtl8812bu_version }}"
  register: rtl8812bu_repo
  retries: 3
  until: not rtl8812bu_repo.failed
- name: change rtl8812bu owner
  file:
    path: /usr/local/src/rtl8812bu
    owner: "{{ ansible_user }}"
    recurse: yes
- include: Debian.yml
  when: ansible_os_family == 'Debian'
- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
- name: disable compile rtl8812bu for i386
  lineinfile:
    path: /usr/local/src/rtl8812bu/Makefile
    regexp: '^CONFIG_PLATFORM_I386_PC'
    line: 'CONFIG_PLATFORM_I386_PC = n'
  when: not rtl8812bu_config_i386
- name: enable compile rtl8812bu for RPI
  lineinfile:
    path: /usr/local/src/rtl8812bu/Makefile
    regexp: '^CONFIG_PLATFORM_ARM_RPI'
    line: 'CONFIG_PLATFORM_ARM_RPI = y'
  when: rtl8812bu_config_rpi
- name: make rtl8812bu
  become: false
  make:
    params:
      NUM_THREADS: "{{ compile_threads }}"
  args:
    chdir: /usr/local/src/rtl8812bu
- name: copy rtl8812bu kernel module
  copy:
    remote_src: yes
    src: /usr/local/src/rtl8812bu/88x2bu.ko
    dest: /lib/modules/{{ ansible_kernel }}/kernel/drivers/net/88x2bu.ko
- name: run depmod for rtl8812au
  command: depmod
- name: install rtl8812bu to kernel
  modprobe:
    name: 88x2bu
    state: present